services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - media_files:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=BLOG.settings_production
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    command: >
      sh -c "python BLOG/manage.py collectstatic --noinput &&
             python BLOG/manage.py migrate &&
             python BLOG/manage.py runserver 0.0.0.0:8000"

volumes:
  media_files:
