services:
  - type: web
    name: blog-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RENDER
        value: "true"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "blog-backend.onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SETTINGS_MODULE
        value: "BLOG.settings"
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: POSTGRES_DB
        value: "blogdb"
      - key: POSTGRES_USER
        value: "bloguser"
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: blog-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: blog-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: blog-db
          property: port
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: ""  # Set this in Render dashboard
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        value: ""  # Set this in Render dashboard
      - key: GOOGLE_OAUTH_REDIRECT_URI
        value: "https://blog-backend.onrender.com/api/user/google-callback/"
      - key: PORT
        value: "8000"

databases:
  - name: blog-db
    plan: free
    databaseName: blogdb
    user: bloguser
