services:
  # Backend API Service (Dockerized)
  - type: web
    name: blog-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "blog-api.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
    healthCheckPath: /health/
    autoDeploy: false

  # Frontend Service (Static Site)
  - type: web
    name: blog-frontend
    runtime: static
    buildCommand: |
      cd frontend &&
      npm ci &&
      npm run build
    staticPublishPath: ./frontend/dist
    plan: free
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: blog-api
          property: host
    routes:
      - type: redirect
        source: /*
        destination: /index.html
    autoDeploy: false

databases:
  - name: blog-db
    databaseName: blog_db
    user: blog_user
    plan: free
