# Generated by Django 5.2 on 2025-04-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_category_user_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
